feat: add `@joshdb/sqlite`
josh-development/providers pull request #140
Opened 2022-09-06 01:05 UTC by RealShadowNova

2022-09-06 07:22 UTC, dan-online requested changes
I haven't read the SQLiteProvider file yet, but first these changes and also add the SQLite data file to gitignore

2022-09-06 07:22 UTC, dan-online commented on .github/workflows/continuous-tests.yml
> +    name: RedisProvider
SQLite

2022-09-06 07:22 UTC, dan-online commented on packages/maria/src/lib/MariaProvider.ts
>    };
Password is needed

2022-09-06 07:22 UTC, dan-online commented on packages/sqlite/package.json
> +  "contributors": [],
Add yourself here

2022-09-06 17:56 UTC, RealShadowNova commented on packages/sqlite/tests/lib/QueryHandler.test.ts
> +    test('GIVEN typeof QueryHandler THEN returns function', () => {
These are just basically placeholders for the tests whenever they haven't been written yet. Never found a reason to remove them everywhere.

2022-09-08 16:07 UTC, RealShadowNova commented on packages/sqlite/src/lib/SQLiteProvider.ts
> +    return process.env.NODE_ENV === 'test' ? { major: 2, minor: 0, patch: 0 } : this.resolveVersion('[VI]{version}[/VI]');
Unless you can find a better way, this is the only way.

2022-09-17 21:23 UTC, dan-online approved these changes
LGTM

2022-09-17 21:24 UTC, merged

2022-09-17 21:29 UTC, dan-online approved these changes
LGTM